backend:
  name: github
  repo: raufsemi/raufsemi.github.io  # your GitHub repo
  branch: main     
  publish_mode: editorial_workflow  

  
media_folder: "static/images/uploads"   # images stored here in repo
public_folder: "/images/uploads"        # url path for images

collections:
  - name: "posts"
    label: "New Post"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { name: "excerpt", label: "Excerpt", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
