backend:
  name: github
  repo: raufsemi/raufsemi.github.io  # your GitHub repo
  branch: main                       # your default branch
  site_domain: raufsemi.com          # your custom domain
  publish_mode: editorial_workflow   # enables editorial workflow (optional)

media_folder: "static/images/uploads"   # where images will be stored in your repo
public_folder: "/images/uploads"        # URL path prefix to your images

collections:
  - name: "posts"
    label: "New Post"
    folder: "posts"                     # folder where your posts will live
    create: true
    # I removed the language filter since you didn't mention multi-language
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # filenames like 2025-05-28-my-post.md
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { name: "excerpt", label: "Excerpt", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
